[package]
name = "solstrale"
version = "0.1.0"
edition = "2021"

[dependencies]
fastrand = "1.8.0"
image = "0.24.5"
simple-error = "0.2.3"
enum_dispatch = "0.3.11"
tobj = "3.2.4"
oidn = "1.4.3"
derive_more = "0.99.17"

[dev-dependencies]
image-compare = "0.2.4"
criterion = "0.4.0"
panic-message = "0.3.0"

[[bench]]
name = "solstrale_benchmark"
harness = false