[package]
name = "solstrale"
description = "A Path tracing library"
version = "0.1.11"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/DanielPettersson/solstrale-rust"
keywords = ["Pathtracing", "Graphics"]
exclude = [
    "resources/*",
    "oidn/*"
]

[features]
oidn-postprocessor = ["dep:oidn"]

[profile.release]
lto = true
codegen-units = 1
debug = 1

[dependencies]
fastrand = "2.3.0"
image = "0.25.5"
simple-error = "0.3.1"
enum_dispatch = "0.3.13"
tobj = "4.0.3"
oidn = { version = "2.2.4", optional = true }
derive_more = { version = "2.0.0", features = ["constructor", "display"] }
rayon = "1.10.0"

[dev-dependencies]
image-compare = "0.4.1"
criterion = "0.5.1"

[[bench]]
name = "solstrale_benchmark"
harness = false