[package]
name = "solstrale"
version = "0.1.0"
edition = "2021"

[dependencies]
fastrand = "1.8.0"
image = "0.24.5"
simple-error = "0.2.3"
enum_dispatch = "0.3.11"
tobj = "3.2.4"
oidn = "1.4.3"

[dev-dependencies]
image-compare = "0.2.4"