name: CI
on: [push, pull_request]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - name: Update apt
        run: sudo apt-get update
      - name: Install libtbb2
        run: sudo apt-get install -y libtbb2
      - name: Copy Oidn lib
        run: sudo cp oidn/lib/libOpenImageDenoise* /usr/lib
      - run: cargo test --all-features
